#!/bin/bash
#$ -M bpage1@nd.edu
#$ -m abe
#$ -cwd
#$ -pe mpi-16 32
##$ -q *@@cswarm
#$ -q long
#$ -o 16task_parabolicfem_9_expanded_results.txt
#$ -e errorurrmahgurd.err
#$ -N ParabolicFem_16task_Tests

module purge
#module load gcc/6.2.0 
#module load mpich/3.2-gcc-6.2.0
#module load mpich/3.2-intel-15.0
module load ompi/2.0.1-gcc-6.2.0

echo "9 tasks per node"
for j in {1..8..1}
  do
    echo "$j threads per task"
    for k in {0..20..1}
      do
        mpirun -np 16 -npernode 9 ./main -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads $j --major-order col --distribution-method splitmatrix
      done
 done
