#!/bin/bash
#$ -M bpage1@nd.edu
#$ -m abe
#$ -cwd
#$ -pe mpi-16 256
##$ -q *@@cswarm
#$ -q long
#$ -o 16task_bmw3_2_results.txt
#$ -e errorurrmahgurd.err
#$ -N BMW3_2_16task_Tests

module purge
#module load gcc/6.2.0 
#module load mpich/3.2-gcc-6.2.0
#module load mpich/3.2-intel-15.0
module load hpx/4.0.0

echo "Bash version ${BASH_VERSION}..."
for i in {1..16..1}
  do 
       
            echo "$j threads per task"
            
            for k in {0..50..1}
                do 
                    mpirun -np 16 -npernode $i ./main -lm ../sample_matrices/bmw3_2.mtx --omp-threads 1 --major-order col --distribution-method splitmatrix
                done
      
 done
