#!/bin/bash
#$ -M bpage1@nd.edu
#$ -m abe
#$ -cwd
#$ -pe mpi-16 192
##$ -q *@@cswarm
#$ -q long
#$ -o 36task_nd24k_3_expanded_results.txt
#$ -e errorurrmahgurd.err
#$ -N ND24K_36task_Tests

module purge
#module load gcc/6.2.0 
#module load mpich/3.2-gcc-6.2.0
#module load mpich/3.2-intel-15.0
#module load hpx/4.0.0
module load ompi/2.0.1-gcc-6.2.0

echo "3 tasks per node"
for j in {1..8..1}
  do
	echo "$j threads per task"
    	for k in {0..20..1}
      	  do
		mpirun -np 36 -npernode 3 ./main -lm ../sample_matrices/nd24k_expanded.mtx --omp-threads $j --major-order col --distribution-method splitmatrix
      	  done
  done