#!/bin/bash
#$ -M bpage1@nd.edu
#$ -m abe
#$ -cwd
#$ -pe mpi-16 112
##$ -q *@@cswarm
#$ -q long
#$ -o 49task_torso1_7_results.txt
#$ -e errorurrmahgurd.err
#$ -N Torso1_49task_7_Tests

module purge
#module load gcc/6.2.0 
#module load mpich/3.2-gcc-6.2.0
#module load mpich/3.2-intel-15.0
#module load hpx/4.0.0
module load ompi/2.0.1-gcc-6.2.0

echo "Bash version ${BASH_VERSION}..."
echo “7 tasks per node"
for i in {1..8..1}
  do 
	echo "$i threads per task"
        for j in {0..50..1}
          do 
        	mpirun -np 49 -npernode 7 ./main -lm ../sample_matrices/torso1.mtx --omp-threads $i --major-order col --distribution-method splitmatrix
          done
  done
