#!/bin/bash
#$ -M bpage1@nd.edu
#$ -m abe
#$ -cwd
#$ -pe mpi-16 64
##$ -q *@@cswarm
#$ -q long
#$ -o 4task_bmw3_2_expanded_results.txt
#$ -e errorurrmahgurd.err
#$ -N BMW3_2_4task_Tests

module purge
#module load gcc/6.2.0 
#module load mpich/3.2-gcc-6.2.0
#module load mpich/3.2-intel-15.0
module load ompi/2.0.1-gcc-6.2.0

echo "Bash version ${BASH_VERSION}..."
for i in {1..4..1}
  do 
     echo "$i tasks per node"
     
     for j in {1..8..1}
        do 
            echo "$j threads per task"
            
            for k in {0..20..1}
                do 
                    mpirun -np 4 -npernode $i ./main -lm ../sample_matrices/bmw3_2_expanded.mtx --omp-threads $j --major-order col --distribution-method splitmatrix
                done
        done
 done
