#!/bin/bash
#$ -M bpage1@nd.edu
#$ -m abe
#$ -cwd
#$ -pe mpi-16 160
##$ -q *@@cswarm
#$ -q long
#$ -o 64task_torso1_7_results.txt
#$ -e errorurrmahgurd.err
#$ -N Torso1_64task_7_Tests

module purge
#module load gcc/6.2.0 
#module load mpich/3.2-gcc-6.2.0
#module load mpich/3.2-intel-15.0
module load hpx/4.0.0


echo “7 tasks per node"
for i in {1..8..1}
  do 
	echo "$j threads per task"
        for k in {0..50..1}
          do 
		mpirun -np 64 -npernode 7 ./main -lm ../sample_matrices/torso1.mtx --omp-threads $i --major-order col --distribution-method splitmatrix
          done
 done
