#!/bin/tcsh
#$ -M bpage1@nd.edu
#$ -m abe
#$ -cwd
#$ -pe mpi-16 1024
##$ -q *@@cswarm
#$ -q long
#$ -o additonal_matrix_verification_results.txt
#$ -e errorurrmahgurd.err
#$ -N Cluster_SpMV_Matrix_Verification_Tests

module purge
#module load gcc/6.2.0
#module load mpich/3.2-gcc-6.2.0
#module load mpich/3.2-intel-15.0
module load hpx/4.0.0
echo "fsync starting"
fsync -d 10 $SGE_STDOUT_PATH &

mpirun -np 4 -npernode 1 ./main -lm ../sample_matrices/torso1.mtx --omp-threads 4 --major-order col --distribution-method splitmatrix
mpirun -np 16 -npernode 1 ./main -lm ../sample_matrices/torso1.mtx --omp-threads 4 --major-order col --distribution-method splitmatrix
mpirun -np 25 -npernode 1 ./main -lm ../sample_matrices/torso1.mtx --omp-threads 4 --major-order col --distribution-method splitmatrix
mpirun -np 36 -npernode 1 ./main -lm ../sample_matrices/torso1.mtx --omp-threads 4 --major-order col --distribution-method splitmatrix
mpirun -np 49 -npernode 1 ./main -lm ../sample_matrices/torso1.mtx --omp-threads 4 --major-order col --distribution-method splitmatrix
mpirun -np 64 -npernode 1 ./main -lm ../sample_matrices/torso1.mtx --omp-threads 4 --major-order col --distribution-method splitmatrix
mpirun -np 4 -npernode 1 ./main -lm ../sample_matrices/bmw3_2.mtx --omp-threads 4 --major-order col --distribution-method splitmatrix
mpirun -np 16 -npernode 1 ./main -lm ../sample_matrices/bmw3_2.mtx --omp-threads 4 --major-order col --distribution-method splitmatrix
mpirun -np 25 -npernode 1 ./main -lm ../sample_matrices/bmw3_2.mtx --omp-threads 4 --major-order col --distribution-method splitmatrix
mpirun -np 36 -npernode 1 ./main -lm ../sample_matrices/bmw3_2.mtx --omp-threads 4 --major-order col --distribution-method splitmatrix
mpirun -np 49 -npernode 1 ./main -lm ../sample_matrices/bmw3_2.mtx --omp-threads 4 --major-order col --distribution-method splitmatrix
mpirun -np 64 -npernode 1 ./main -lm ../sample_matrices/bmw3_2.mtx --omp-threads 4 --major-order col --distribution-method splitmatrix
mpirun -np 4 -npernode 1 ./main -lm ../sample_matrices/nd24k.mtx --omp-threads 4 --major-order col --distribution-method splitmatrix
mpirun -np 16 -npernode 1 ./main -lm ../sample_matrices/nd24k.mtx --omp-threads 4 --major-order col --distribution-method splitmatrix
mpirun -np 25 -npernode 1 ./main -lm ../sample_matrices/nd24k.mtx --omp-threads 4 --major-order col --distribution-method splitmatrix
mpirun -np 36 -npernode 1 ./main -lm ../sample_matrices/nd24k.mtx --omp-threads 4 --major-order col --distribution-method splitmatrix
mpirun -np 49 -npernode 1 ./main -lm ../sample_matrices/nd24k.mtx --omp-threads 4 --major-order col --distribution-method splitmatrix
mpirun -np 64 -npernode 1 ./main -lm ../sample_matrices/nd24k.mtx --omp-threads 4 --major-order col --distribution-method splitmatrix
mpirun -np 4 -npernode 1 ./main -lm ../sample_matrices/FullChip.mtx --omp-threads 4 --major-order col --distribution-method splitmatrix
mpirun -np 16 -npernode 1 ./main -lm ../sample_matrices/FullChip.mtx --omp-threads 4 --major-order col --distribution-method splitmatrix
mpirun -np 25 -npernode 1 ./main -lm ../sample_matrices/FullChip.mtx --omp-threads 4 --major-order col --distribution-method splitmatrix
mpirun -np 36 -npernode 1 ./main -lm ../sample_matrices/FullChip.mtx --omp-threads 4 --major-order col --distribution-method splitmatrix
mpirun -np 49 -npernode 1 ./main -lm ../sample_matrices/FullChip.mtx --omp-threads 4 --major-order col --distribution-method splitmatrix
mpirun -np 64 -npernode 1 ./main -lm ../sample_matrices/FullChip.mtx --omp-threads 4 --major-order col --distribution-method splitmatrix
