#!/bin/tcsh
#$ -M bpage1@nd.edu
#$ -m abe
#$ -cwd
#$ -pe mpi-16 64
##$ -q *@@cswarm
#$ -q long
#$ -o test.out
#$ -e errorurrmahgurd.err
#$ -N Cluster_SpMV_ParabolicFem_Tests

module purge
#module load gcc/6.2.0 
#module load mpich/3.2-gcc-6.2.0
#module load mpich/3.2-intel-15.0
module load hpx/4.0.0

mpirun -np 4 -npernode 2 ./main -lm ../sample_matrices/parabolic_fem.mtx --omp-threads 1 --major-order col --distribution-method splitmatrix
mpirun -np 4 -npernode 4 ./main -lm ../sample_matrices/parabolic_fem.mtx --omp-threads 1 --major-order col --distribution-method splitmatrix

