#!/bin/bash
#$ -M bpage1@nd.edu
#$ -m abe
#$ -cwd
#$ -pe mpi-16 64
##$ -q *@@cswarm
#$ -q long
#$ -o test.out
#$ -e errorurrmahgurd.err
#$ -N Cluster_SpMV_ParabolicFem_Tests

module purge
#module load gcc/6.2.0 
#module load mpich/3.2-gcc-6.2.0
#module load mpich/3.2-intel-15.0
module load hpx/4.0.0

echo "Bash version ${BASH_VERSION}..."
for i in {0..10..2}
  do 
     echo "Welcome $i times"
 done
