#!/bin/tcsh
#$ -M bpage1@nd.edu
#$ -m abe
#$ -cwd
#$ -pe mpi-16 16
##$ -q *@@cswarm
#$ -q long
#$ -o expandmatricesOutput.txt
#$ -e errorurrmahgurd.err
#$ -N Expand_Symmetric_Matrices

module purge
#module load mvapich2/2.2-intel-17.1-mlx
module load gcc/7.1.0
#fsync -d 10 $SGE_STDOUT_PATH &

set matrix = "parabolic_fem CurlCurl_3 offshore nlpkkt80 CO gsm_106857 msdoor bmw3_2 BenElechi1 t3dh F2 consph SiO2 torso1 dielFilterV3real m_t1 crankseg_2 nd24k mouse_gene human_gene1"

foreach m ($matrix)
  echo "Expanding $m"
  ./symmetricExpander -i ../sample_matrices/${m}.mtx -o ../sample_matrices/${m}_expanded.mtx
end
