#!/bin/tcsh
#$ -M bpage1@nd.edu
#$ -m abe
#$ -cwd
#$ -pe mpi-16 32
##$ -q *@@cswarm
#$ -q long
#$ -o 4proc_no_barriers_mva_balanced_optimized.csv
#$ -e errorurrmahgurd.err
#$ -N NoBarrierTests_4

module purge
module load mvapich2/2.2-gcc-7.1.0-mlx
#fsync -d 10 $SGE_STDOUT_PATH &

set matrix = "atmosmodd parabolic_fem_expanded rajat30 CurlCurl_3_expanded offshore_expanded FEM_3D_thermal2 nlpkkt80_expanded CO_expanded gsm_106857_expanded msdoor_expanded bmw3_2_expanded BenElechi1_expanded t3dh_expanded F2_expanded consph_expanded SiO2_expanded torso1_expanded dielFilterV3real RM07R m_t1_expanded crankseg_2_expanded nd24k_expanded TSOPF_RS_b2383 mouse_gene_expanded human_gene1_expanded"

foreach m ($matrix)
  mpirun -np 4 -ppn 2 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket -genv MV2_ENABLE_SHARP=1 -genv SHARP_COLL_ENABLE_GROUP_TRIM=0 -genv MV2_RNDV_PROTOCOL=R3 -genv MV2_USE_LAZY_MEM_UNREGISTER=0 -genv MV2_USE_SHARED_MEM=1 -genv MP_COLLECTIVE_OFFLOAD=all ./main -lm ../sample_matrices/$m.mtx --omp-threads 8 --distribution-method balanced
  mpirun -np 4 -ppn 2 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket -genv MV2_ENABLE_SHARP=1 -genv SHARP_COLL_ENABLE_GROUP_TRIM=0 -genv MV2_RNDV_PROTOCOL=R3 -genv MV2_USE_LAZY_MEM_UNREGISTER=0 -genv MV2_USE_SHARED_MEM=1 -genv MP_COLLECTIVE_OFFLOAD=all ./main -lm ../sample_matrices/$m.mtx --omp-threads 8 --distribution-method balanced
  mpirun -np 4 -ppn 2 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket -genv MV2_ENABLE_SHARP=1 -genv SHARP_COLL_ENABLE_GROUP_TRIM=0 -genv MV2_RNDV_PROTOCOL=R3 -genv MV2_USE_LAZY_MEM_UNREGISTER=0 -genv MV2_USE_SHARED_MEM=1 -genv MP_COLLECTIVE_OFFLOAD=all ./main -lm ../sample_matrices/$m.mtx --omp-threads 8 --distribution-method balanced
  mpirun -np 4 -ppn 2 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket -genv MV2_ENABLE_SHARP=1 -genv SHARP_COLL_ENABLE_GROUP_TRIM=0 -genv MV2_RNDV_PROTOCOL=R3 -genv MV2_USE_LAZY_MEM_UNREGISTER=0 -genv MV2_USE_SHARED_MEM=1 -genv MP_COLLECTIVE_OFFLOAD=all ./main -lm ../sample_matrices/$m.mtx --omp-threads 8 --distribution-method balanced
  mpirun -np 4 -ppn 2 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket -genv MV2_ENABLE_SHARP=1 -genv SHARP_COLL_ENABLE_GROUP_TRIM=0 -genv MV2_RNDV_PROTOCOL=R3 -genv MV2_USE_LAZY_MEM_UNREGISTER=0 -genv MV2_USE_SHARED_MEM=1 -genv MP_COLLECTIVE_OFFLOAD=all ./main -lm ../sample_matrices/$m.mtx --omp-threads 8 --distribution-method balanced
  mpirun -np 4 -ppn 2 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket -genv MV2_ENABLE_SHARP=1 -genv SHARP_COLL_ENABLE_GROUP_TRIM=0 -genv MV2_RNDV_PROTOCOL=R3 -genv MV2_USE_LAZY_MEM_UNREGISTER=0 -genv MV2_USE_SHARED_MEM=1 -genv MP_COLLECTIVE_OFFLOAD=all ./main -lm ../sample_matrices/$m.mtx --omp-threads 8 --distribution-method balanced
  mpirun -np 4 -ppn 2 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket -genv MV2_ENABLE_SHARP=1 -genv SHARP_COLL_ENABLE_GROUP_TRIM=0 -genv MV2_RNDV_PROTOCOL=R3 -genv MV2_USE_LAZY_MEM_UNREGISTER=0 -genv MV2_USE_SHARED_MEM=1 -genv MP_COLLECTIVE_OFFLOAD=all ./main -lm ../sample_matrices/$m.mtx --omp-threads 8 --distribution-method balanced
  mpirun -np 4 -ppn 2 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket -genv MV2_ENABLE_SHARP=1 -genv SHARP_COLL_ENABLE_GROUP_TRIM=0 -genv MV2_RNDV_PROTOCOL=R3 -genv MV2_USE_LAZY_MEM_UNREGISTER=0 -genv MV2_USE_SHARED_MEM=1 -genv MP_COLLECTIVE_OFFLOAD=all ./main -lm ../sample_matrices/$m.mtx --omp-threads 8 --distribution-method balanced
  mpirun -np 4 -ppn 2 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket -genv MV2_ENABLE_SHARP=1 -genv SHARP_COLL_ENABLE_GROUP_TRIM=0 -genv MV2_RNDV_PROTOCOL=R3 -genv MV2_USE_LAZY_MEM_UNREGISTER=0 -genv MV2_USE_SHARED_MEM=1 -genv MP_COLLECTIVE_OFFLOAD=all ./main -lm ../sample_matrices/$m.mtx --omp-threads 8 --distribution-method balanced
  mpirun -np 4 -ppn 2 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket -genv MV2_ENABLE_SHARP=1 -genv SHARP_COLL_ENABLE_GROUP_TRIM=0 -genv MV2_RNDV_PROTOCOL=R3 -genv MV2_USE_LAZY_MEM_UNREGISTER=0 -genv MV2_USE_SHARED_MEM=1 -genv MP_COLLECTIVE_OFFLOAD=all ./main -lm ../sample_matrices/$m.mtx --omp-threads 8 --distribution-method balanced
  echo "\n\n"
end

