#!/bin/tcsh
#$ -M bpage1@nd.edu
#$ -m abe
#$ -cwd
#$ -pe mpi-16 16
##$ -q *@@cswarm
#$ -q long
#$ -o 1proc_barriers_mva_balanced_varyingThreadCounts.csv
#$ -e errorurrmahgurd.err
#$ -N BarrierTests_1

module purge
module load mvapich2/2.2-gcc-7.1.0-mlx
#fsync -d 10 $SGE_STDOUT_PATH &

set matrix = "atmosmodd parabolic_fem_expanded rajat30 CurlCurl_3_expanded offshore_expanded FEM_3D_thermal2 nlpkkt80_expanded CO_expanded gsm_106857_expanded msdoor_expanded bmw3_2_expanded BenElechi1_expanded t3dh_expanded F2_expanded consph_expanded SiO2_expanded torso1_expanded dielFilterV3real RM07R m_t1_expanded crankseg_2_expanded nd24k_expanded TSOPF_RS_b2383 mouse_gene_expanded human_gene1_expanded"

#foreach m ($matrix)
#  mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket  ./main -lm ../sample_matrices/$m.mtx --omp-threads 8 --use-barriers true --distribution-method balanced
#  mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket  ./main -lm ../sample_matrices/$m.mtx --omp-threads 8 --use-barriers true --distribution-method balanced
#  mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket  ./main -lm ../sample_matrices/$m.mtx --omp-threads 8 --use-barriers true --distribution-method balanced
#  mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket  ./main -lm ../sample_matrices/$m.mtx --omp-threads 8 --use-barriers true --distribution-method balanced
#  mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket  ./main -lm ../sample_matrices/$m.mtx --omp-threads 8 --use-barriers true --distribution-method balanced
#  mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket  ./main -lm ../sample_matrices/$m.mtx --omp-threads 8 --use-barriers true --distribution-method balanced
#  mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket  ./main -lm ../sample_matrices/$m.mtx --omp-threads 8 --use-barriers true --distribution-method balanced
#  mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket  ./main -lm ../sample_matrices/$m.mtx --omp-threads 8 --use-barriers true --distribution-method balanced
#  mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket  ./main -lm ../sample_matrices/$m.mtx --omp-threads 8 --use-barriers true --distribution-method balanced
#  mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket  ./main -lm ../sample_matrices/$m.mtx --omp-threads 8 --use-barriers true --distribution-method balanced
#  echo "\n\n"
#end

mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 1 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 1 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 1 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 1 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 1 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 1 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 1 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 1 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 1 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 1 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 1 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 1 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 1 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 1 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 1 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 1 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 1 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 1 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 1 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 1 --use-barriers true --distribution-method bv2
echo "\n\n"
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 2 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 2 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 2 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 2 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 2 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 2 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 2 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 2 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 2 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 2 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 2 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 2 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 2 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 2 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 2 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 2 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 2 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 2 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 2 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 2 --use-barriers true --distribution-method bv2
echo "\n\n"
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 3 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 3 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 3 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 3 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 3 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 3 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 3 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 3 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 3 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 3 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 3 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 3 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 3 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 3 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 3 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 3 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 3 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 3 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 3 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 3 --use-barriers true --distribution-method bv2
echo "\n\n"
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 4 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 4 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 4 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 4 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 4 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 4 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 4 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 4 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 4 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 4 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 4 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 4 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 4 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 4 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 4 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 4 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 4 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 4 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 4 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 4 --use-barriers true --distribution-method bv2
echo "\n\n"
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 5 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 5 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 5 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 5 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 5 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 5 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 5 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 5 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 5 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 5 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 5 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 5 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 5 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 5 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 5 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 5 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 5 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 5 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 5 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 5 --use-barriers true --distribution-method bv2
echo "\n\n"
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 6 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 6 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 6 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 6 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 6 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 6 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 6 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 6 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 6 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 6 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 6 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 6 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 6 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 6 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 6 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 6 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 6 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 6 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 6 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 6 --use-barriers true --distribution-method bv2
echo "\n\n"
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 7 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 7 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 7 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 7 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 7 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 7 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 7 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 7 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 7 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 7 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 7 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 7 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 7 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 7 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 7 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 7 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 7 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 7 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 7 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 7 --use-barriers true --distribution-method bv2
echo "\n\n"
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 8 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 8 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 8 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 8 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 8 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 8 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 8 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 8 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 8 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 8 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 8 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 8 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 8 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 8 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 8 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 8 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 8 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 8 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 8 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 8 --use-barriers true --distribution-method bv2
echo "\n\n"
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 9 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 9 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 9 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 9 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 9 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 9 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 9 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 9 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 9 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 9 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 9 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 9 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 9 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 9 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 9 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 9 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 9 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 9 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 9 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 9 --use-barriers true --distribution-method bv2
echo "\n\n"
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 10 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 10 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 10 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 10 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 10 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 10 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 10 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 10 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 10 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 10 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 10 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 10 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 10 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 10 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 10 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 10 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 10 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 10 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 10 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 10 --use-barriers true --distribution-method bv2
echo "\n\n"
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 11 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 11 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 11 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 11 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 11 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 11 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 11 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 11 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 11 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 11 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 11 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 11 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 11 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 11 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 11 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 11 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 11 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 11 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 11 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 11 --use-barriers true --distribution-method bv2
echo "\n\n"
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 12 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 12 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 12 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 12 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 12 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 12 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 12 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 12 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 12 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 12 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 12 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 12 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 12 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 12 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 12 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 12 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 12 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 12 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 12 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 12 --use-barriers true --distribution-method bv2
echo "\n\n"
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 13 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 13 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 13 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 13 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 13 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 13 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 13 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 13 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 13 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 13 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 13 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 13 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 13 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 13 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 13 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 13 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 13 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 13 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 13 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 13 --use-barriers true --distribution-method bv2
echo "\n\n"
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 14 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 14 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 14 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 14 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 14 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 14 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 14 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 14 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 14 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 14 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 14 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 14 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 14 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 14 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 14 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 14 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 14 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 14 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 14 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 14 --use-barriers true --distribution-method bv2
echo "\n\n"
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 15 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 15 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 15 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 15 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 15 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 15 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 15 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 15 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 15 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 15 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 15 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 15 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 15 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 15 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 15 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 15 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 15 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 15 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 15 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 15 --use-barriers true --distribution-method bv2
echo "\n\n"
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 16 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 16 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 16 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 16 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 16 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 16 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 16 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 16 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 16 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 16 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 16 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 16 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 16 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 16 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 16 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 16 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 16 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 16 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 16 --use-barriers true --distribution-method bv2
mpirun -np 1 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket ./mainTest -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 16 --use-barriers true --distribution-method bv2
echo "\n\n"
