#!/bin/tcsh
#$ -M bpage1@nd.edu
#$ -m abe
#$ -cwd
#$ -pe mpi-16 32
##$ -q *@@cswarm
#$ -q long
#$ -o optimizeCorrectness_4.txt
#$ -e errorurrmahgurd.err
#$ -N Correctness_Tests

module purge
module unload mvapich2
module load mvapich2/2.2-gcc-7.1.0-mlx
#fsync -d 10 $SGE_STDOUT_PATH &

set matrix = "atmosmodd parabolic_fem_expanded rajat30 CurlCurl_3_expanded offshore_expanded FEM_3D_thermal2 nlpkkt80_expanded CO_expanded gsm_106857_expanded msdoor_expanded bmw3_2_expanded BenElechi1_expanded t3dh_expanded F2_expanded consph_expanded SiO2_expanded torso1_expanded dielFilterV3real RM07R m_t1_expanded crankseg_2_expanded nd24k_expanded TSOPF_RS_b2383 mouse_gene_expanded human_gene1_expanded"

#foreach m ($matrix)
#  echo "Starting Tests on $m"
#mpirun -np 4 -npernode 2 -x OMP_PROC_BIND=true ./main -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 8 --use-barriers true
#end

#mpirun -np 4 -ppn 2 ./main -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 8 --use-barriers true
#mpirun -np 4 -ppn 2 -env MV2_USE_RDMA_FAST_PATH=0 -env MV2_SHOW_CPU_BINDING=1 ./main -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 1 --use-barriers true -debug true

#mpirun -np 4 -ppn 2 -env MV2_CPU_BINDING_LEVEL=socket -env MV2_CPU_BINDING_POLICY=scatter -env MV2_ENABLE_AFFINITY=0 -env OMP_NUM_THREADS=8 -env MV2_SHOW_CPU_BINDING=1 ./main -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 8 --use-barriers true

mpirun -np 4 -ppn 2 -genv MV2_ENABLE_AFFINITY=0 -genv OMP_NUM_THREADS=8 -bind-to socket -map-by socket  ./main -lm ../sample_matrices/parabolic_fem_expanded.mtx --omp-threads 8 --use-barriers true
