#!/bin/bash
#$ -M bpage1@nd.edu
#$ -m abe
#$ -cwd
#$ -pe mpi-16 256
##$ -q *@@cswarm
#$ -q long
#$ -o 16task_nd24k_results.txt
#$ -e errorurrmahgurd.err
#$ -N ND24K_16task_Tests

module purge
#module load gcc/6.2.0 
#module load mpich/3.2-gcc-6.2.0
#module load mpich/3.2-intel-15.0
module load ompi/2.0.1-gcc-6.2.0

echo "Bash version ${BASH_VERSION}..."
for i in {1..16..1}
  do 
	echo "$i tasks per node"
	for j in {1..8..1}	
	  do		
		echo "$j threads per task"
            	for k in {0..50..1}
                  do 
                	mpirun -np 16 -npernode $i ./main -lm ../sample_matrices/nd24k.mtx --omp-threads $j --major-order col --distribution-method splitmatrix
                done
      	  done
 done
