#!/bin/bash
#$ -M bpage1@nd.edu
#$ -m abe
#$ -cwd
#$ -pe mpi-16 144
##$ -q *@@cswarm
#$ -q long
#$ -o 9task_parabolicfem_results.txt
#$ -e errorurrmahgurd.err
#$ -N ParabolicFem_9task_Tests

module purge
#module load gcc/6.2.0 
#module load mpich/3.2-gcc-6.2.0
#module load mpich/3.2-intel-15.0
module load hpx/4.0.0

echo "Bash version ${BASH_VERSION}..."
for i in {1..9..1}
  do 
     echo "$i tasks per node"
     
     for j in {1..8..1}
        do 
            echo "$j threads per task"
            
            for k in {0..50..1}
                do 
                    mpirun -np 9 -npernode $i ./main -lm ../sample_matrices/parabolic_fem.mtx --omp-threads $j --major-order col --distribution-method splitmatrix
                done
        done
 done
